use crate::i18n::text as t;
use crate::paths::MiyuPaths;
use anyhow::{bail, Result};
use std::path::{Path, PathBuf};

const BEGIN_MARKER: &str = "# >>> miyu powershell hook >>>";
const END_MARKER: &str = "# <<< miyu powershell hook <<<";
const UTF8_BOM: &[u8] = &[0xEF, 0xBB, 0xBF];

pub fn hook(executable: &Path) -> String {
    let executable = powershell_quote(executable);
    format!(
        r#"# Miyu integration for Windows PowerShell.
# This file is generated by `miyu powershell-init`.

function global:miyu {{
    & {executable} @args
}}

Import-Module PSReadLine -ErrorAction SilentlyContinue
if (Get-Module PSReadLine) {{
    Set-PSReadLineKeyHandler -Key Enter -ScriptBlock {{
        param($key, $arg)

        $line = $null
        $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        if ([string]::IsNullOrWhiteSpace($line) -or $line.Contains("`n") -or $line.Contains("`r")) {{
            [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
            return
        }}

        $tokens = $null
        $parseErrors = $null
        [System.Management.Automation.Language.Parser]::ParseInput(
            $line,
            [ref]$tokens,
            [ref]$parseErrors
        ) | Out-Null
        $commandToken = $tokens |
            Where-Object {{ $_.TokenFlags -band [System.Management.Automation.Language.TokenFlags]::CommandName }} |
            Select-Object -First 1

        if ($null -eq $commandToken -or
            $null -ne (Get-Command -Name $commandToken.Text -ErrorAction SilentlyContinue)) {{
            [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
            return
        }}

        & {executable} --shell-classify --shell powershell -- $line *> $null
        if ($LASTEXITCODE -eq 0) {{
            [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
            return
        }}

        $escapedLine = $line.Replace("'", "''")
        $replacement = "& {executable} --shell-intercept --shell powershell -- '$escapedLine'"
        [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $replacement)
        [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
    }}
}}
"#
    )
}

pub fn install(paths: &MiyuPaths) -> Result<()> {
    let executable = std::env::current_exe()?;
    let hook_file = hook_file(paths);
    if let Some(parent) = hook_file.parent() {
        std::fs::create_dir_all(parent)?;
    }
    write_utf8_bom(&hook_file, &hook(&executable))?;

    let profile = profile_path();
    let backup = backup_profile_if_needed(&profile)?;
    append_source_block(&profile, &hook_file)?;

    println!(
        "{}: {}",
        t(
            "installed Windows PowerShell hook",
            "已安装 Windows PowerShell hook"
        ),
        hook_file.display()
    );
    println!("{}: {}", t("updated", "已更新"), profile.display());
    if let Some(backup) = backup {
        println!(
            "{}: {}",
            t("profile backup", "Profile 备份"),
            backup.display()
        );
    }
    println!(
        "{}",
        t(
            "open a new Windows PowerShell window for the hook to take effect",
            "请新开一个 Windows PowerShell 窗口使 hook 生效"
        )
    );
    Ok(())
}

pub fn uninstall(paths: &MiyuPaths) -> Result<bool> {
    let hook_file = hook_file(paths);
    let removed_file = remove_file_if_exists(&hook_file)?;
    let profile = profile_path();
    let removed_block = remove_source_block(&profile)?;
    let removed = removed_file || removed_block;
    if removed {
        println!(
            "{}: PowerShell",
            t("removed Miyu shell hook", "已移除 Miyu shell hook")
        );
        println!(
            "{}",
            t(
                "open a new Windows PowerShell window to finish unloading it",
                "请新开一个 Windows PowerShell 窗口以完成卸载"
            )
        );
    }
    Ok(removed)
}

pub fn hook_file(paths: &MiyuPaths) -> PathBuf {
    paths.config_dir.join("shell/powershell-hook.ps1")
}

pub fn profile_path() -> PathBuf {
    if let Some(path) = std::env::var_os("MIYU_POWERSHELL_PROFILE") {
        return PathBuf::from(path);
    }
    directories::UserDirs::new()
        .and_then(|dirs| dirs.document_dir().map(Path::to_path_buf))
        .or_else(|| directories::BaseDirs::new().map(|dirs| dirs.home_dir().join("Documents")))
        .unwrap_or_else(|| PathBuf::from("Documents"))
        .join("WindowsPowerShell/Microsoft.PowerShell_profile.ps1")
}

fn powershell_quote(path: &Path) -> String {
    format!("'{}'", path.display().to_string().replace('\'', "''"))
}

fn append_source_block(profile: &Path, hook_file: &Path) -> Result<()> {
    let mut existing = read_utf8(profile)?.unwrap_or_default();
    if existing.contains(BEGIN_MARKER) && existing.contains(END_MARKER) {
        return Ok(());
    }
    if let Some(parent) = profile.parent() {
        std::fs::create_dir_all(parent)?;
    }
    if !existing.is_empty() && !existing.ends_with('\n') {
        existing.push_str("\r\n");
    }
    existing.push_str(BEGIN_MARKER);
    existing.push_str("\r\n. ");
    existing.push_str(&powershell_quote(hook_file));
    existing.push_str("\r\n");
    existing.push_str(END_MARKER);
    existing.push_str("\r\n");
    write_utf8_bom(profile, &existing)
}

fn remove_source_block(profile: &Path) -> Result<bool> {
    let Some(existing) = read_utf8(profile)? else {
        return Ok(false);
    };
    let Some(begin_index) = existing.find(BEGIN_MARKER) else {
        return Ok(false);
    };
    let Some(end_relative) = existing[begin_index..].find(END_MARKER) else {
        return Ok(false);
    };
    let mut end_index = begin_index + end_relative + END_MARKER.len();
    if existing.as_bytes().get(end_index) == Some(&b'\r') {
        end_index += 1;
    }
    if existing.as_bytes().get(end_index) == Some(&b'\n') {
        end_index += 1;
    }
    let mut updated = String::new();
    updated.push_str(&existing[..begin_index]);
    updated.push_str(&existing[end_index..]);
    write_utf8_bom(profile, &updated)?;
    Ok(true)
}

fn backup_profile_if_needed(profile: &Path) -> Result<Option<PathBuf>> {
    if !profile.is_file() {
        return Ok(None);
    }
    let backup = PathBuf::from(format!("{}.miyu-backup", profile.display()));
    if !backup.exists() {
        std::fs::copy(profile, &backup)?;
        Ok(Some(backup))
    } else {
        Ok(None)
    }
}

fn read_utf8(path: &Path) -> Result<Option<String>> {
    let bytes = match std::fs::read(path) {
        Ok(bytes) => bytes,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error.into()),
    };
    let bytes = bytes.strip_prefix(UTF8_BOM).unwrap_or(&bytes);
    match String::from_utf8(bytes.to_vec()) {
        Ok(content) => Ok(Some(content)),
        Err(_) => bail!(
            "PowerShell profile is not UTF-8; refusing to rewrite it: {}",
            path.display()
        ),
    }
}

fn write_utf8_bom(path: &Path, content: &str) -> Result<()> {
    let mut bytes = Vec::with_capacity(UTF8_BOM.len() + content.len());
    bytes.extend_from_slice(UTF8_BOM);
    bytes.extend_from_slice(content.as_bytes());
    std::fs::write(path, bytes)?;
    Ok(())
}

fn remove_file_if_exists(path: &Path) -> Result<bool> {
    match std::fs::remove_file(path) {
        Ok(()) => Ok(true),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(error.into()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hook_uses_psreadline_and_preserves_valid_commands() {
        let hook = hook(Path::new(r"C:\Program Files\Miyu\miyu.exe"));
        assert!(hook.contains("Set-PSReadLineKeyHandler -Key Enter"));
        assert!(hook.contains("Get-Command -Name $commandToken.Text"));
        assert!(hook.contains("--shell-classify --shell powershell"));
        assert!(hook.contains("--shell-intercept --shell powershell"));
        assert!(hook.contains("'C:\\Program Files\\Miyu\\miyu.exe'"));
    }

    #[test]
    fn profile_block_roundtrips_without_losing_existing_content() {
        let temp = tempfile::tempdir().unwrap();
        let profile = temp.path().join("profile.ps1");
        let hook_file = temp.path().join("powershell-hook.ps1");
        write_utf8_bom(&profile, "function before { 'ok' }\r\n").unwrap();

        append_source_block(&profile, &hook_file).unwrap();
        append_source_block(&profile, &hook_file).unwrap();
        let installed = read_utf8(&profile).unwrap().unwrap();
        assert_eq!(installed.matches(BEGIN_MARKER).count(), 1);
        assert!(installed.contains("function before"));
        assert!(installed.contains("powershell-hook.ps1"));

        assert!(remove_source_block(&profile).unwrap());
        assert!(!remove_source_block(&profile).unwrap());
        assert_eq!(
            read_utf8(&profile).unwrap().unwrap(),
            "function before { 'ok' }\r\n"
        );
    }
}
